// Code generated by Fern. DO NOT EDIT.

package client

import (
    achievements "github.com/trophyso/trophy-go/achievements"
    client "github.com/trophyso/trophy-go/admin/client"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    leaderboards "github.com/trophyso/trophy-go/leaderboards"
    metrics "github.com/trophyso/trophy-go/metrics"
    option "github.com/trophyso/trophy-go/option"
    points "github.com/trophyso/trophy-go/points"
    streaks "github.com/trophyso/trophy-go/streaks"
    users "github.com/trophyso/trophy-go/users"
)


type Client struct {
    Achievements *achievements.Client
    Metrics *metrics.Client
    Users *users.Client
    Streaks *streaks.Client
    Points *points.Client
    Leaderboards *leaderboards.Client
    Admin *client.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
    options := core.NewRequestOptions(opts...)
    if options.SdkVersion == "" {
        options.SdkVersion = "1.19.0"
    }
    return &Client{
        Achievements: achievements.NewClient(options),
        Metrics: metrics.NewClient(options),
        Users: users.NewClient(options),
        Streaks: streaks.NewClient(options),
        Points: points.NewClient(options),
        Leaderboards: leaderboards.NewClient(options),
        Admin: client.NewClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

