// This file was auto-generated by Fern from our API Definition.

package client

import (
	achievements "github.com/trophyso/trophy-go/achievements"
	core "github.com/trophyso/trophy-go/core"
	internal "github.com/trophyso/trophy-go/internal"
	metrics "github.com/trophyso/trophy-go/metrics"
	option "github.com/trophyso/trophy-go/option"
	points "github.com/trophyso/trophy-go/points"
	users "github.com/trophyso/trophy-go/users"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Achievements *achievements.Client
	Metrics      *metrics.Client
	Users        *users.Client
	Points       *points.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:       options.ToHeader(),
		Achievements: achievements.NewClient(opts...),
		Metrics:      metrics.NewClient(opts...),
		Users:        users.NewClient(opts...),
		Points:       points.NewClient(opts...),
	}
}
