// This file was auto-generated by Fern from our API Definition.

package client

import (
	achievements "go-mod-path/generated/go/achievements"
	core "go-mod-path/generated/go/core"
	internal "go-mod-path/generated/go/internal"
	metrics "go-mod-path/generated/go/metrics"
	option "go-mod-path/generated/go/option"
	users "go-mod-path/generated/go/users"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Achievements *achievements.Client
	Metrics      *metrics.Client
	Users        *users.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:       options.ToHeader(),
		Achievements: achievements.NewClient(opts...),
		Metrics:      metrics.NewClient(opts...),
		Users:        users.NewClient(opts...),
	}
}
