// Code generated by Fern. DO NOT EDIT.

package achievements

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.17.0"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Get all achievements and their completion stats.
func (c *Client) All(
    ctx context.Context,
    request *trophygo.AchievementsAllRequest,
    opts ...option.RequestOption,
) ([]*trophygo.AchievementWithStatsResponse, error){
    response, err := c.WithRawResponse.All(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Mark an achievement as completed for a user.
func (c *Client) Complete(
    ctx context.Context,
    // Unique reference of the achievement as set when created.
    key string,
    request *trophygo.AchievementsCompleteRequest,
    opts ...option.RequestOption,
) (*trophygo.AchievementCompletionResponse, error){
    response, err := c.WithRawResponse.Complete(
        ctx,
        key,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

