// Code generated by Fern. DO NOT EDIT.

package achievements

import (
    context "context"
    http "net/http"

    trophygo "github.com/trophyso/trophy-go"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

func (r *RawClient) All(
    ctx context.Context,
    request *trophygo.AchievementsAllRequest,
    opts ...option.RequestOption,
) (*core.Response[[]*trophygo.AchievementWithStatsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Api",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Api",
        ),
        "https://api.trophy.so/v1",
    )
    endpointURL := baseURL + "/achievements"
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response []*trophygo.AchievementWithStatsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(trophygo.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[[]*trophygo.AchievementWithStatsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Complete(
    ctx context.Context,
    // Unique reference of the achievement as set when created.
    key string,
    request *trophygo.AchievementsCompleteRequest,
    opts ...option.RequestOption,
) (*core.Response[*trophygo.AchievementCompletionResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Api",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Api",
        ),
        "https://api.trophy.so/v1",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/achievements/%v/complete",
        key,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *trophygo.AchievementCompletionResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            DisableRetries: options.DisableRetries,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(trophygo.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*trophygo.AchievementCompletionResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

