// Code generated by Fern. DO NOT EDIT.

package metrics_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    require "github.com/stretchr/testify/require"
    trophygo "github.com/trophyso/trophy-go"
    client "github.com/trophyso/trophy-go/client"
    option "github.com/trophyso/trophy-go/option"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestMetricsEventWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &trophygo.MetricsEventRequest{
            IdempotencyKey: trophygo.String(
                "e4296e4b-8493-4bd1-9c30-5a1a9ac4d78f",
            ),
            User: &trophygo.UpsertedUser{
                Email: trophygo.String(
                    "user@example.com",
                ),
                Tz: trophygo.String(
                    "Europe/London",
                ),
                Attributes: map[string]string{
                    "department": "engineering",
                    "role": "developer",
                },
                Id: "18",
            },
            Value: 750,
            Attributes: map[string]string{
                "category": "writing",
                "source": "mobile-app",
            },
        }
    _, invocationErr :=     client.Metrics.Event(
            context.TODO(),
            "words-written",
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestMetricsEventWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestMetricsEventWithWireMock", "POST", "/metrics/words-written/event", nil, 1)
}


