// This file was auto-generated by Fern from our API Definition.

package freezes

import (
	context "context"
	trophygo "github.com/trophyso/trophy-go"
	streaks "github.com/trophyso/trophy-go/admin/streaks"
	core "github.com/trophyso/trophy-go/core"
	internal "github.com/trophyso/trophy-go/internal"
	option "github.com/trophyso/trophy-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Create streak freezes for multiple users.
func (c *Client) Create(
	ctx context.Context,
	request *streaks.CreateStreakFreezesRequest,
	opts ...option.RequestOption,
) (*trophygo.CreateStreakFreezesResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://admin.trophy.so/v1",
	)
	endpointURL := baseURL + "/streaks/freezes"
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		400: func(apiError *core.APIError) error {
			return &trophygo.BadRequestError{
				APIError: apiError,
			}
		},
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response *trophygo.CreateStreakFreezesResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
