// Code generated by Fern. DO NOT EDIT.

package api

// Environment defines the environment with multiple base URLs.
type Environment struct {
	Api   string
	Admin string
}

// Environments defines all of the API environments.
// These values can be used with the WithBaseURL
// RequestOption to override the client's default environment,
// if any.
var Environments = struct {
	Production Environment
}{
	Production: Environment{
		Admin: "https://admin.trophy.so/v1",
		Api:   "https://api.trophy.so/v1",
	},
}
