// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersAchievementsAllRequest(t *testing.T) {
	t.Run("SetUserAttributes", func(t *testing.T) {
		obj := &AchievementsAllRequest{}
		var fernTestValueUserAttributes *string
		obj.SetUserAttributes(fernTestValueUserAttributes)
		assert.Equal(t, fernTestValueUserAttributes, obj.UserAttributes)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAchievementsAllRequest(t *testing.T) {
	t.Run("SetUserAttributes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementsAllRequest{}
		var fernTestValueUserAttributes *string

		// Act
		obj.SetUserAttributes(fernTestValueUserAttributes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAchievementsCompleteRequest(t *testing.T) {
	t.Run("SetUser", func(t *testing.T) {
		obj := &AchievementsCompleteRequest{}
		var fernTestValueUser *UpsertedUser
		obj.SetUser(fernTestValueUser)
		assert.Equal(t, fernTestValueUser, obj.User)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAchievementsCompleteRequest(t *testing.T) {
	t.Run("SetUser_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementsCompleteRequest{}
		var fernTestValueUser *UpsertedUser

		// Act
		obj.SetUser(fernTestValueUser)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAchievementCompletionResponse(t *testing.T) {
	t.Run("SetCompletionId", func(t *testing.T) {
		obj := &AchievementCompletionResponse{}
		var fernTestValueCompletionId string
		obj.SetCompletionId(fernTestValueCompletionId)
		assert.Equal(t, fernTestValueCompletionId, obj.CompletionId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAchievement", func(t *testing.T) {
		obj := &AchievementCompletionResponse{}
		var fernTestValueAchievement *UserAchievementResponse
		obj.SetAchievement(fernTestValueAchievement)
		assert.Equal(t, fernTestValueAchievement, obj.Achievement)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPoints", func(t *testing.T) {
		obj := &AchievementCompletionResponse{}
		var fernTestValuePoints map[string]*MetricEventPointsResponse
		obj.SetPoints(fernTestValuePoints)
		assert.Equal(t, fernTestValuePoints, obj.Points)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAchievementCompletionResponse(t *testing.T) {
	t.Run("GetCompletionId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		var expected string
		obj.CompletionId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCompletionId(), "getter should return the property value")
	})

	t.Run("GetCompletionId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AchievementCompletionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCompletionId() // Should return zero value
	})

	t.Run("GetAchievement", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		var expected *UserAchievementResponse
		obj.Achievement = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAchievement(), "getter should return the property value")
	})

	t.Run("GetAchievement_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		obj.Achievement = nil

		// Act & Assert
		assert.Nil(t, obj.GetAchievement(), "getter should return nil when property is nil")
	})

	t.Run("GetAchievement_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AchievementCompletionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAchievement() // Should return zero value
	})

	t.Run("GetPoints", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		var expected map[string]*MetricEventPointsResponse
		obj.Points = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPoints(), "getter should return the property value")
	})

	t.Run("GetPoints_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		obj.Points = nil

		// Act & Assert
		assert.Nil(t, obj.GetPoints(), "getter should return nil when property is nil")
	})

	t.Run("GetPoints_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AchievementCompletionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPoints() // Should return zero value
	})

}

func TestSettersMarkExplicitAchievementCompletionResponse(t *testing.T) {
	t.Run("SetCompletionId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		var fernTestValueCompletionId string

		// Act
		obj.SetCompletionId(fernTestValueCompletionId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAchievement_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		var fernTestValueAchievement *UserAchievementResponse

		// Act
		obj.SetAchievement(fernTestValueAchievement)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPoints_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}
		var fernTestValuePoints map[string]*MetricEventPointsResponse

		// Act
		obj.SetPoints(fernTestValuePoints)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAchievementCompletionResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AchievementCompletionResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AchievementCompletionResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AchievementCompletionResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AchievementCompletionResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAchievementCompletionResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AchievementCompletionResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AchievementCompletionResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesAchievementCompletionResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AchievementCompletionResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AchievementCompletionResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
