// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/trophyso/trophy-go/internal"
	big "math/big"
)

var (
	leaderboardsAllRequestFieldIncludeFinished = big.NewInt(1 << 0)
)

type LeaderboardsAllRequest struct {
	// When set to 'true', leaderboards with status 'finished' will be included in the response. By default, finished leaderboards are excluded.
	IncludeFinished *bool `json:"-" url:"includeFinished,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LeaderboardsAllRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetIncludeFinished sets the IncludeFinished field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllRequest) SetIncludeFinished(includeFinished *bool) {
	l.IncludeFinished = includeFinished
	l.require(leaderboardsAllRequestFieldIncludeFinished)
}

var (
	leaderboardsGetRequestFieldOffset         = big.NewInt(1 << 0)
	leaderboardsGetRequestFieldLimit          = big.NewInt(1 << 1)
	leaderboardsGetRequestFieldRun            = big.NewInt(1 << 2)
	leaderboardsGetRequestFieldUserId         = big.NewInt(1 << 3)
	leaderboardsGetRequestFieldUserAttributes = big.NewInt(1 << 4)
)

type LeaderboardsGetRequest struct {
	// Number of rankings to skip for pagination.
	Offset *int `json:"-" url:"offset,omitempty"`
	// Maximum number of rankings to return. Cannot be greater than the size of the leaderboard.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Specific run date in YYYY-MM-DD format. If not provided, returns the current run.
	Run *string `json:"-" url:"run,omitempty"`
	// When provided, offset is relative to this user's position on the leaderboard. If the user is not found in the leaderboard, returns empty rankings array.
	UserId *string `json:"-" url:"userId,omitempty"`
	// Attribute key and value to filter the rankings by, separated by a colon. For example, `city:London`. This parameter is required, and only valid for leaderboards with a breakdown attribute.
	UserAttributes *string `json:"-" url:"userAttributes,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LeaderboardsGetRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsGetRequest) SetOffset(offset *int) {
	l.Offset = offset
	l.require(leaderboardsGetRequestFieldOffset)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsGetRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(leaderboardsGetRequestFieldLimit)
}

// SetRun sets the Run field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsGetRequest) SetRun(run *string) {
	l.Run = run
	l.require(leaderboardsGetRequestFieldRun)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsGetRequest) SetUserId(userId *string) {
	l.UserId = userId
	l.require(leaderboardsGetRequestFieldUserId)
}

// SetUserAttributes sets the UserAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsGetRequest) SetUserAttributes(userAttributes *string) {
	l.UserAttributes = userAttributes
	l.require(leaderboardsGetRequestFieldUserAttributes)
}

// A user's ranking in a leaderboard.
var (
	leaderboardRankingFieldUserId   = big.NewInt(1 << 0)
	leaderboardRankingFieldUserName = big.NewInt(1 << 1)
	leaderboardRankingFieldRank     = big.NewInt(1 << 2)
	leaderboardRankingFieldValue    = big.NewInt(1 << 3)
)

type LeaderboardRanking struct {
	// The ID of the user.
	UserId string `json:"userId" url:"userId"`
	// The name of the user. May be null if no name is set.
	UserName *string `json:"userName,omitempty" url:"userName,omitempty"`
	// The user's rank in the leaderboard.
	Rank int `json:"rank" url:"rank"`
	// The user's value for this leaderboard (points, metric value, etc.).
	Value int `json:"value" url:"value"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardRanking) GetUserId() string {
	if l == nil {
		return ""
	}
	return l.UserId
}

func (l *LeaderboardRanking) GetUserName() *string {
	if l == nil {
		return nil
	}
	return l.UserName
}

func (l *LeaderboardRanking) GetRank() int {
	if l == nil {
		return 0
	}
	return l.Rank
}

func (l *LeaderboardRanking) GetValue() int {
	if l == nil {
		return 0
	}
	return l.Value
}

func (l *LeaderboardRanking) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardRanking) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardRanking) SetUserId(userId string) {
	l.UserId = userId
	l.require(leaderboardRankingFieldUserId)
}

// SetUserName sets the UserName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardRanking) SetUserName(userName *string) {
	l.UserName = userName
	l.require(leaderboardRankingFieldUserName)
}

// SetRank sets the Rank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardRanking) SetRank(rank int) {
	l.Rank = rank
	l.require(leaderboardRankingFieldRank)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardRanking) SetValue(value int) {
	l.Value = value
	l.require(leaderboardRankingFieldValue)
}

func (l *LeaderboardRanking) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardRanking
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardRanking(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardRanking) MarshalJSON() ([]byte, error) {
	type embed LeaderboardRanking
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardRanking) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	leaderboardResponseWithRankingsFieldId                  = big.NewInt(1 << 0)
	leaderboardResponseWithRankingsFieldName                = big.NewInt(1 << 1)
	leaderboardResponseWithRankingsFieldKey                 = big.NewInt(1 << 2)
	leaderboardResponseWithRankingsFieldRankBy              = big.NewInt(1 << 3)
	leaderboardResponseWithRankingsFieldBreakdownAttribute  = big.NewInt(1 << 4)
	leaderboardResponseWithRankingsFieldBreakdownAttributes = big.NewInt(1 << 5)
	leaderboardResponseWithRankingsFieldMetricKey           = big.NewInt(1 << 6)
	leaderboardResponseWithRankingsFieldMetricName          = big.NewInt(1 << 7)
	leaderboardResponseWithRankingsFieldPointsSystemKey     = big.NewInt(1 << 8)
	leaderboardResponseWithRankingsFieldPointsSystemName    = big.NewInt(1 << 9)
	leaderboardResponseWithRankingsFieldDescription         = big.NewInt(1 << 10)
	leaderboardResponseWithRankingsFieldStart               = big.NewInt(1 << 11)
	leaderboardResponseWithRankingsFieldEnd                 = big.NewInt(1 << 12)
	leaderboardResponseWithRankingsFieldStartTime           = big.NewInt(1 << 13)
	leaderboardResponseWithRankingsFieldEndTime             = big.NewInt(1 << 14)
	leaderboardResponseWithRankingsFieldMaxParticipants     = big.NewInt(1 << 15)
	leaderboardResponseWithRankingsFieldRunUnit             = big.NewInt(1 << 16)
	leaderboardResponseWithRankingsFieldRunInterval         = big.NewInt(1 << 17)
	leaderboardResponseWithRankingsFieldStatus              = big.NewInt(1 << 18)
	leaderboardResponseWithRankingsFieldRankings            = big.NewInt(1 << 19)
)

type LeaderboardResponseWithRankings struct {
	// The unique ID of the leaderboard.
	Id string `json:"id" url:"id"`
	// The user-facing name of the leaderboard.
	Name string `json:"name" url:"name"`
	// The unique key used to reference the leaderboard in APIs.
	Key string `json:"key" url:"key"`
	// What the leaderboard ranks by.
	RankBy LeaderboardResponseRankBy `json:"rankBy" url:"rankBy"`
	// Deprecated. The key of the attribute to break down this leaderboard by.
	BreakdownAttribute *string `json:"breakdownAttribute,omitempty" url:"breakdownAttribute,omitempty"`
	// The user attribute keys that this leaderboard is broken down by.
	BreakdownAttributes []string `json:"breakdownAttributes" url:"breakdownAttributes"`
	// The key of the metric to rank by, if rankBy is 'metric'.
	MetricKey *string `json:"metricKey,omitempty" url:"metricKey,omitempty"`
	// The name of the metric to rank by, if rankBy is 'metric'.
	MetricName *string `json:"metricName,omitempty" url:"metricName,omitempty"`
	// The key of the points system to rank by, if rankBy is 'points'.
	PointsSystemKey *string `json:"pointsSystemKey,omitempty" url:"pointsSystemKey,omitempty"`
	// The name of the points system to rank by, if rankBy is 'points'.
	PointsSystemName *string `json:"pointsSystemName,omitempty" url:"pointsSystemName,omitempty"`
	// The user-facing description of the leaderboard.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The start date of the leaderboard in YYYY-MM-DD format.
	Start string `json:"start" url:"start"`
	// The end date of the leaderboard in YYYY-MM-DD format, or null if it runs forever.
	End *string `json:"end,omitempty" url:"end,omitempty"`
	// When set, ranking only counts activity at or after this time of day in the user's timezone (HH:mm format).
	StartTime *string `json:"startTime,omitempty" url:"startTime,omitempty"`
	// When set, ranking only counts activity before this time of day in the user's timezone (HH:mm format).
	EndTime *string `json:"endTime,omitempty" url:"endTime,omitempty"`
	// The maximum number of participants in the leaderboard.
	MaxParticipants *int `json:"maxParticipants,omitempty" url:"maxParticipants,omitempty"`
	// The repetition type for recurring leaderboards, or null for one-time leaderboards.
	RunUnit *LeaderboardResponseRunUnit `json:"runUnit,omitempty" url:"runUnit,omitempty"`
	// The interval between repetitions, relative to the start date and repetition type. Null for one-time leaderboards.
	RunInterval *int `json:"runInterval,omitempty" url:"runInterval,omitempty"`
	// The status of the leaderboard.
	Status LeaderboardResponseWithRankingsStatus `json:"status" url:"status"`
	// Array of user rankings for the leaderboard.
	Rankings []*LeaderboardRanking `json:"rankings" url:"rankings"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardResponseWithRankings) GetId() string {
	if l == nil {
		return ""
	}
	return l.Id
}

func (l *LeaderboardResponseWithRankings) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *LeaderboardResponseWithRankings) GetKey() string {
	if l == nil {
		return ""
	}
	return l.Key
}

func (l *LeaderboardResponseWithRankings) GetRankBy() LeaderboardResponseRankBy {
	if l == nil {
		return ""
	}
	return l.RankBy
}

func (l *LeaderboardResponseWithRankings) GetBreakdownAttribute() *string {
	if l == nil {
		return nil
	}
	return l.BreakdownAttribute
}

func (l *LeaderboardResponseWithRankings) GetBreakdownAttributes() []string {
	if l == nil {
		return nil
	}
	return l.BreakdownAttributes
}

func (l *LeaderboardResponseWithRankings) GetMetricKey() *string {
	if l == nil {
		return nil
	}
	return l.MetricKey
}

func (l *LeaderboardResponseWithRankings) GetMetricName() *string {
	if l == nil {
		return nil
	}
	return l.MetricName
}

func (l *LeaderboardResponseWithRankings) GetPointsSystemKey() *string {
	if l == nil {
		return nil
	}
	return l.PointsSystemKey
}

func (l *LeaderboardResponseWithRankings) GetPointsSystemName() *string {
	if l == nil {
		return nil
	}
	return l.PointsSystemName
}

func (l *LeaderboardResponseWithRankings) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LeaderboardResponseWithRankings) GetStart() string {
	if l == nil {
		return ""
	}
	return l.Start
}

func (l *LeaderboardResponseWithRankings) GetEnd() *string {
	if l == nil {
		return nil
	}
	return l.End
}

func (l *LeaderboardResponseWithRankings) GetStartTime() *string {
	if l == nil {
		return nil
	}
	return l.StartTime
}

func (l *LeaderboardResponseWithRankings) GetEndTime() *string {
	if l == nil {
		return nil
	}
	return l.EndTime
}

func (l *LeaderboardResponseWithRankings) GetMaxParticipants() *int {
	if l == nil {
		return nil
	}
	return l.MaxParticipants
}

func (l *LeaderboardResponseWithRankings) GetRunUnit() *LeaderboardResponseRunUnit {
	if l == nil {
		return nil
	}
	return l.RunUnit
}

func (l *LeaderboardResponseWithRankings) GetRunInterval() *int {
	if l == nil {
		return nil
	}
	return l.RunInterval
}

func (l *LeaderboardResponseWithRankings) GetStatus() LeaderboardResponseWithRankingsStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *LeaderboardResponseWithRankings) GetRankings() []*LeaderboardRanking {
	if l == nil {
		return nil
	}
	return l.Rankings
}

func (l *LeaderboardResponseWithRankings) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardResponseWithRankings) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetId(id string) {
	l.Id = id
	l.require(leaderboardResponseWithRankingsFieldId)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetName(name string) {
	l.Name = name
	l.require(leaderboardResponseWithRankingsFieldName)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetKey(key string) {
	l.Key = key
	l.require(leaderboardResponseWithRankingsFieldKey)
}

// SetRankBy sets the RankBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetRankBy(rankBy LeaderboardResponseRankBy) {
	l.RankBy = rankBy
	l.require(leaderboardResponseWithRankingsFieldRankBy)
}

// SetBreakdownAttribute sets the BreakdownAttribute field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetBreakdownAttribute(breakdownAttribute *string) {
	l.BreakdownAttribute = breakdownAttribute
	l.require(leaderboardResponseWithRankingsFieldBreakdownAttribute)
}

// SetBreakdownAttributes sets the BreakdownAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetBreakdownAttributes(breakdownAttributes []string) {
	l.BreakdownAttributes = breakdownAttributes
	l.require(leaderboardResponseWithRankingsFieldBreakdownAttributes)
}

// SetMetricKey sets the MetricKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetMetricKey(metricKey *string) {
	l.MetricKey = metricKey
	l.require(leaderboardResponseWithRankingsFieldMetricKey)
}

// SetMetricName sets the MetricName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetMetricName(metricName *string) {
	l.MetricName = metricName
	l.require(leaderboardResponseWithRankingsFieldMetricName)
}

// SetPointsSystemKey sets the PointsSystemKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetPointsSystemKey(pointsSystemKey *string) {
	l.PointsSystemKey = pointsSystemKey
	l.require(leaderboardResponseWithRankingsFieldPointsSystemKey)
}

// SetPointsSystemName sets the PointsSystemName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetPointsSystemName(pointsSystemName *string) {
	l.PointsSystemName = pointsSystemName
	l.require(leaderboardResponseWithRankingsFieldPointsSystemName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetDescription(description *string) {
	l.Description = description
	l.require(leaderboardResponseWithRankingsFieldDescription)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetStart(start string) {
	l.Start = start
	l.require(leaderboardResponseWithRankingsFieldStart)
}

// SetEnd sets the End field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetEnd(end *string) {
	l.End = end
	l.require(leaderboardResponseWithRankingsFieldEnd)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetStartTime(startTime *string) {
	l.StartTime = startTime
	l.require(leaderboardResponseWithRankingsFieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetEndTime(endTime *string) {
	l.EndTime = endTime
	l.require(leaderboardResponseWithRankingsFieldEndTime)
}

// SetMaxParticipants sets the MaxParticipants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetMaxParticipants(maxParticipants *int) {
	l.MaxParticipants = maxParticipants
	l.require(leaderboardResponseWithRankingsFieldMaxParticipants)
}

// SetRunUnit sets the RunUnit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetRunUnit(runUnit *LeaderboardResponseRunUnit) {
	l.RunUnit = runUnit
	l.require(leaderboardResponseWithRankingsFieldRunUnit)
}

// SetRunInterval sets the RunInterval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetRunInterval(runInterval *int) {
	l.RunInterval = runInterval
	l.require(leaderboardResponseWithRankingsFieldRunInterval)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetStatus(status LeaderboardResponseWithRankingsStatus) {
	l.Status = status
	l.require(leaderboardResponseWithRankingsFieldStatus)
}

// SetRankings sets the Rankings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardResponseWithRankings) SetRankings(rankings []*LeaderboardRanking) {
	l.Rankings = rankings
	l.require(leaderboardResponseWithRankingsFieldRankings)
}

func (l *LeaderboardResponseWithRankings) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardResponseWithRankings
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardResponseWithRankings(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardResponseWithRankings) MarshalJSON() ([]byte, error) {
	type embed LeaderboardResponseWithRankings
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardResponseWithRankings) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The status of the leaderboard.
type LeaderboardResponseWithRankingsStatus string

const (
	LeaderboardResponseWithRankingsStatusActive    LeaderboardResponseWithRankingsStatus = "active"
	LeaderboardResponseWithRankingsStatusScheduled LeaderboardResponseWithRankingsStatus = "scheduled"
	LeaderboardResponseWithRankingsStatusFinished  LeaderboardResponseWithRankingsStatus = "finished"
)

func NewLeaderboardResponseWithRankingsStatusFromString(s string) (LeaderboardResponseWithRankingsStatus, error) {
	switch s {
	case "active":
		return LeaderboardResponseWithRankingsStatusActive, nil
	case "scheduled":
		return LeaderboardResponseWithRankingsStatusScheduled, nil
	case "finished":
		return LeaderboardResponseWithRankingsStatusFinished, nil
	}
	var t LeaderboardResponseWithRankingsStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LeaderboardResponseWithRankingsStatus) Ptr() *LeaderboardResponseWithRankingsStatus {
	return &l
}

var (
	leaderboardsAllResponseItemFieldId                  = big.NewInt(1 << 0)
	leaderboardsAllResponseItemFieldName                = big.NewInt(1 << 1)
	leaderboardsAllResponseItemFieldKey                 = big.NewInt(1 << 2)
	leaderboardsAllResponseItemFieldRankBy              = big.NewInt(1 << 3)
	leaderboardsAllResponseItemFieldBreakdownAttribute  = big.NewInt(1 << 4)
	leaderboardsAllResponseItemFieldBreakdownAttributes = big.NewInt(1 << 5)
	leaderboardsAllResponseItemFieldMetricKey           = big.NewInt(1 << 6)
	leaderboardsAllResponseItemFieldMetricName          = big.NewInt(1 << 7)
	leaderboardsAllResponseItemFieldPointsSystemKey     = big.NewInt(1 << 8)
	leaderboardsAllResponseItemFieldPointsSystemName    = big.NewInt(1 << 9)
	leaderboardsAllResponseItemFieldDescription         = big.NewInt(1 << 10)
	leaderboardsAllResponseItemFieldStart               = big.NewInt(1 << 11)
	leaderboardsAllResponseItemFieldEnd                 = big.NewInt(1 << 12)
	leaderboardsAllResponseItemFieldStartTime           = big.NewInt(1 << 13)
	leaderboardsAllResponseItemFieldEndTime             = big.NewInt(1 << 14)
	leaderboardsAllResponseItemFieldMaxParticipants     = big.NewInt(1 << 15)
	leaderboardsAllResponseItemFieldRunUnit             = big.NewInt(1 << 16)
	leaderboardsAllResponseItemFieldRunInterval         = big.NewInt(1 << 17)
	leaderboardsAllResponseItemFieldStatus              = big.NewInt(1 << 18)
)

type LeaderboardsAllResponseItem struct {
	// The unique ID of the leaderboard.
	Id string `json:"id" url:"id"`
	// The user-facing name of the leaderboard.
	Name string `json:"name" url:"name"`
	// The unique key used to reference the leaderboard in APIs.
	Key string `json:"key" url:"key"`
	// What the leaderboard ranks by.
	RankBy LeaderboardResponseRankBy `json:"rankBy" url:"rankBy"`
	// Deprecated. The key of the attribute to break down this leaderboard by.
	BreakdownAttribute *string `json:"breakdownAttribute,omitempty" url:"breakdownAttribute,omitempty"`
	// The user attribute keys that this leaderboard is broken down by.
	BreakdownAttributes []string `json:"breakdownAttributes" url:"breakdownAttributes"`
	// The key of the metric to rank by, if rankBy is 'metric'.
	MetricKey *string `json:"metricKey,omitempty" url:"metricKey,omitempty"`
	// The name of the metric to rank by, if rankBy is 'metric'.
	MetricName *string `json:"metricName,omitempty" url:"metricName,omitempty"`
	// The key of the points system to rank by, if rankBy is 'points'.
	PointsSystemKey *string `json:"pointsSystemKey,omitempty" url:"pointsSystemKey,omitempty"`
	// The name of the points system to rank by, if rankBy is 'points'.
	PointsSystemName *string `json:"pointsSystemName,omitempty" url:"pointsSystemName,omitempty"`
	// The user-facing description of the leaderboard.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The start date of the leaderboard in YYYY-MM-DD format.
	Start string `json:"start" url:"start"`
	// The end date of the leaderboard in YYYY-MM-DD format, or null if it runs forever.
	End *string `json:"end,omitempty" url:"end,omitempty"`
	// When set, ranking only counts activity at or after this time of day in the user's timezone (HH:mm format).
	StartTime *string `json:"startTime,omitempty" url:"startTime,omitempty"`
	// When set, ranking only counts activity before this time of day in the user's timezone (HH:mm format).
	EndTime *string `json:"endTime,omitempty" url:"endTime,omitempty"`
	// The maximum number of participants in the leaderboard.
	MaxParticipants *int `json:"maxParticipants,omitempty" url:"maxParticipants,omitempty"`
	// The repetition type for recurring leaderboards, or null for one-time leaderboards.
	RunUnit *LeaderboardResponseRunUnit `json:"runUnit,omitempty" url:"runUnit,omitempty"`
	// The interval between repetitions, relative to the start date and repetition type. Null for one-time leaderboards.
	RunInterval *int `json:"runInterval,omitempty" url:"runInterval,omitempty"`
	// The status of the leaderboard.
	Status LeaderboardsAllResponseItemStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LeaderboardsAllResponseItem) GetId() string {
	if l == nil {
		return ""
	}
	return l.Id
}

func (l *LeaderboardsAllResponseItem) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *LeaderboardsAllResponseItem) GetKey() string {
	if l == nil {
		return ""
	}
	return l.Key
}

func (l *LeaderboardsAllResponseItem) GetRankBy() LeaderboardResponseRankBy {
	if l == nil {
		return ""
	}
	return l.RankBy
}

func (l *LeaderboardsAllResponseItem) GetBreakdownAttribute() *string {
	if l == nil {
		return nil
	}
	return l.BreakdownAttribute
}

func (l *LeaderboardsAllResponseItem) GetBreakdownAttributes() []string {
	if l == nil {
		return nil
	}
	return l.BreakdownAttributes
}

func (l *LeaderboardsAllResponseItem) GetMetricKey() *string {
	if l == nil {
		return nil
	}
	return l.MetricKey
}

func (l *LeaderboardsAllResponseItem) GetMetricName() *string {
	if l == nil {
		return nil
	}
	return l.MetricName
}

func (l *LeaderboardsAllResponseItem) GetPointsSystemKey() *string {
	if l == nil {
		return nil
	}
	return l.PointsSystemKey
}

func (l *LeaderboardsAllResponseItem) GetPointsSystemName() *string {
	if l == nil {
		return nil
	}
	return l.PointsSystemName
}

func (l *LeaderboardsAllResponseItem) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LeaderboardsAllResponseItem) GetStart() string {
	if l == nil {
		return ""
	}
	return l.Start
}

func (l *LeaderboardsAllResponseItem) GetEnd() *string {
	if l == nil {
		return nil
	}
	return l.End
}

func (l *LeaderboardsAllResponseItem) GetStartTime() *string {
	if l == nil {
		return nil
	}
	return l.StartTime
}

func (l *LeaderboardsAllResponseItem) GetEndTime() *string {
	if l == nil {
		return nil
	}
	return l.EndTime
}

func (l *LeaderboardsAllResponseItem) GetMaxParticipants() *int {
	if l == nil {
		return nil
	}
	return l.MaxParticipants
}

func (l *LeaderboardsAllResponseItem) GetRunUnit() *LeaderboardResponseRunUnit {
	if l == nil {
		return nil
	}
	return l.RunUnit
}

func (l *LeaderboardsAllResponseItem) GetRunInterval() *int {
	if l == nil {
		return nil
	}
	return l.RunInterval
}

func (l *LeaderboardsAllResponseItem) GetStatus() LeaderboardsAllResponseItemStatus {
	if l == nil {
		return ""
	}
	return l.Status
}

func (l *LeaderboardsAllResponseItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LeaderboardsAllResponseItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetId(id string) {
	l.Id = id
	l.require(leaderboardsAllResponseItemFieldId)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetName(name string) {
	l.Name = name
	l.require(leaderboardsAllResponseItemFieldName)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetKey(key string) {
	l.Key = key
	l.require(leaderboardsAllResponseItemFieldKey)
}

// SetRankBy sets the RankBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetRankBy(rankBy LeaderboardResponseRankBy) {
	l.RankBy = rankBy
	l.require(leaderboardsAllResponseItemFieldRankBy)
}

// SetBreakdownAttribute sets the BreakdownAttribute field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetBreakdownAttribute(breakdownAttribute *string) {
	l.BreakdownAttribute = breakdownAttribute
	l.require(leaderboardsAllResponseItemFieldBreakdownAttribute)
}

// SetBreakdownAttributes sets the BreakdownAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetBreakdownAttributes(breakdownAttributes []string) {
	l.BreakdownAttributes = breakdownAttributes
	l.require(leaderboardsAllResponseItemFieldBreakdownAttributes)
}

// SetMetricKey sets the MetricKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetMetricKey(metricKey *string) {
	l.MetricKey = metricKey
	l.require(leaderboardsAllResponseItemFieldMetricKey)
}

// SetMetricName sets the MetricName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetMetricName(metricName *string) {
	l.MetricName = metricName
	l.require(leaderboardsAllResponseItemFieldMetricName)
}

// SetPointsSystemKey sets the PointsSystemKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetPointsSystemKey(pointsSystemKey *string) {
	l.PointsSystemKey = pointsSystemKey
	l.require(leaderboardsAllResponseItemFieldPointsSystemKey)
}

// SetPointsSystemName sets the PointsSystemName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetPointsSystemName(pointsSystemName *string) {
	l.PointsSystemName = pointsSystemName
	l.require(leaderboardsAllResponseItemFieldPointsSystemName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetDescription(description *string) {
	l.Description = description
	l.require(leaderboardsAllResponseItemFieldDescription)
}

// SetStart sets the Start field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetStart(start string) {
	l.Start = start
	l.require(leaderboardsAllResponseItemFieldStart)
}

// SetEnd sets the End field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetEnd(end *string) {
	l.End = end
	l.require(leaderboardsAllResponseItemFieldEnd)
}

// SetStartTime sets the StartTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetStartTime(startTime *string) {
	l.StartTime = startTime
	l.require(leaderboardsAllResponseItemFieldStartTime)
}

// SetEndTime sets the EndTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetEndTime(endTime *string) {
	l.EndTime = endTime
	l.require(leaderboardsAllResponseItemFieldEndTime)
}

// SetMaxParticipants sets the MaxParticipants field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetMaxParticipants(maxParticipants *int) {
	l.MaxParticipants = maxParticipants
	l.require(leaderboardsAllResponseItemFieldMaxParticipants)
}

// SetRunUnit sets the RunUnit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetRunUnit(runUnit *LeaderboardResponseRunUnit) {
	l.RunUnit = runUnit
	l.require(leaderboardsAllResponseItemFieldRunUnit)
}

// SetRunInterval sets the RunInterval field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetRunInterval(runInterval *int) {
	l.RunInterval = runInterval
	l.require(leaderboardsAllResponseItemFieldRunInterval)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsAllResponseItem) SetStatus(status LeaderboardsAllResponseItemStatus) {
	l.Status = status
	l.require(leaderboardsAllResponseItemFieldStatus)
}

func (l *LeaderboardsAllResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler LeaderboardsAllResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LeaderboardsAllResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LeaderboardsAllResponseItem) MarshalJSON() ([]byte, error) {
	type embed LeaderboardsAllResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LeaderboardsAllResponseItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// The status of the leaderboard.
type LeaderboardsAllResponseItemStatus string

const (
	LeaderboardsAllResponseItemStatusActive    LeaderboardsAllResponseItemStatus = "active"
	LeaderboardsAllResponseItemStatusScheduled LeaderboardsAllResponseItemStatus = "scheduled"
	LeaderboardsAllResponseItemStatusFinished  LeaderboardsAllResponseItemStatus = "finished"
)

func NewLeaderboardsAllResponseItemStatusFromString(s string) (LeaderboardsAllResponseItemStatus, error) {
	switch s {
	case "active":
		return LeaderboardsAllResponseItemStatusActive, nil
	case "scheduled":
		return LeaderboardsAllResponseItemStatusScheduled, nil
	case "finished":
		return LeaderboardsAllResponseItemStatusFinished, nil
	}
	var t LeaderboardsAllResponseItemStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LeaderboardsAllResponseItemStatus) Ptr() *LeaderboardsAllResponseItemStatus {
	return &l
}
