// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/trophyso/trophy-go/internal"
)

type MetricsEventRequest struct {
	// The user that triggered the event.
	User *UpsertedUser `json:"user,omitempty" url:"-"`
	// The value to add to the user's current total for the given metric.
	Value float64 `json:"value" url:"-"`
}

type EventResponse struct {
	// The unique ID of the event.
	EventId string `json:"eventId" url:"eventId"`
	// The unique ID of the metric that was updated.
	MetricId string `json:"metricId" url:"metricId"`
	// The user's new total progress against the metric.
	Total float64 `json:"total" url:"total"`
	// Achievements completed as a result of this event.
	Achievements []*CompletedAchievementResponse `json:"achievements,omitempty" url:"achievements,omitempty"`
	// The user's current streak for the metric, if the metric has streaks enabled.
	CurrentStreak *MetricEventStreakResponse `json:"currentStreak,omitempty" url:"currentStreak,omitempty"`
	// The points added by this event, and a breakdown of the points awards that added points.
	Points *MetricEventPointsResponse `json:"points,omitempty" url:"points,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventResponse) GetEventId() string {
	if e == nil {
		return ""
	}
	return e.EventId
}

func (e *EventResponse) GetMetricId() string {
	if e == nil {
		return ""
	}
	return e.MetricId
}

func (e *EventResponse) GetTotal() float64 {
	if e == nil {
		return 0
	}
	return e.Total
}

func (e *EventResponse) GetAchievements() []*CompletedAchievementResponse {
	if e == nil {
		return nil
	}
	return e.Achievements
}

func (e *EventResponse) GetCurrentStreak() *MetricEventStreakResponse {
	if e == nil {
		return nil
	}
	return e.CurrentStreak
}

func (e *EventResponse) GetPoints() *MetricEventPointsResponse {
	if e == nil {
		return nil
	}
	return e.Points
}

func (e *EventResponse) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EventResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EventResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventResponse) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type MetricEventPointsResponse struct {
	// The user's total points
	Total *float64 `json:"total,omitempty" url:"total,omitempty"`
	// Array of trigger awards that added points.
	Awards []*PointsAward `json:"awards,omitempty" url:"awards,omitempty"`
	// The points added by this event.
	Added *float64 `json:"added,omitempty" url:"added,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MetricEventPointsResponse) GetTotal() *float64 {
	if m == nil {
		return nil
	}
	return m.Total
}

func (m *MetricEventPointsResponse) GetAwards() []*PointsAward {
	if m == nil {
		return nil
	}
	return m.Awards
}

func (m *MetricEventPointsResponse) GetAdded() *float64 {
	if m == nil {
		return nil
	}
	return m.Added
}

func (m *MetricEventPointsResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MetricEventPointsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MetricEventPointsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MetricEventPointsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MetricEventPointsResponse) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
