// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/trophyso/trophy-go/internal"
)

type PointsBoostsRequest struct {
	// When set to 'true', boosts that have finished (past their end date) will be included in the response. By default, finished boosts are excluded.
	IncludeFinished *bool `json:"-" url:"includeFinished,omitempty"`
}

type PointsSummaryRequest struct {
	// Optional colon-delimited user attribute filters in the format attribute:value,attribute:value. Only users matching ALL specified attributes will be included in the points breakdown.
	UserAttributes *string `json:"-" url:"userAttributes,omitempty"`
}

// A breakdown of users by level in a points system.
type PointsLevelSummaryResponse = []*PointsLevelSummaryResponseItem

type PointsLevelSummaryResponseItem struct {
	Level *PointsLevel `json:"level,omitempty" url:"level,omitempty"`
	// The number of users currently at this level
	Users int `json:"users" url:"users"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PointsLevelSummaryResponseItem) GetLevel() *PointsLevel {
	if p == nil {
		return nil
	}
	return p.Level
}

func (p *PointsLevelSummaryResponseItem) GetUsers() int {
	if p == nil {
		return 0
	}
	return p.Users
}

func (p *PointsLevelSummaryResponseItem) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PointsLevelSummaryResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler PointsLevelSummaryResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PointsLevelSummaryResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PointsLevelSummaryResponseItem) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PointsRange struct {
	// The start of the points range. Inclusive.
	From int `json:"from" url:"from"`
	// The end of the points range. Inclusive.
	To int `json:"to" url:"to"`
	// The number of users in this points range.
	Users int `json:"users" url:"users"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PointsRange) GetFrom() int {
	if p == nil {
		return 0
	}
	return p.From
}

func (p *PointsRange) GetTo() int {
	if p == nil {
		return 0
	}
	return p.To
}

func (p *PointsRange) GetUsers() int {
	if p == nil {
		return 0
	}
	return p.Users
}

func (p *PointsRange) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PointsRange) UnmarshalJSON(data []byte) error {
	type unmarshaler PointsRange
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PointsRange(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PointsRange) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// A list of eleven points ranges, with the first starting and ending at 0, and the remaining 10 being calculated as 10 equally sized ranges from 1 to the greatest number of points a user has, rounded up to the nearest power of 10.
type PointsSummaryResponse = []*PointsRange

type PointsSystemResponse struct {
	// The unique ID of the points system.
	Id string `json:"id" url:"id"`
	// The name of the points system.
	Name string `json:"name" url:"name"`
	// The description of the points system.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// The URL of the badge image for the points system, if one has been uploaded.
	BadgeUrl *string `json:"badgeUrl,omitempty" url:"badgeUrl,omitempty"`
	// The maximum number of points a user can be awarded in this points system
	MaxPoints *float64 `json:"maxPoints,omitempty" url:"maxPoints,omitempty"`
	// Array of active triggers for this points system.
	Triggers []*PointsTrigger `json:"triggers,omitempty" url:"triggers,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PointsSystemResponse) GetId() string {
	if p == nil {
		return ""
	}
	return p.Id
}

func (p *PointsSystemResponse) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PointsSystemResponse) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PointsSystemResponse) GetBadgeUrl() *string {
	if p == nil {
		return nil
	}
	return p.BadgeUrl
}

func (p *PointsSystemResponse) GetMaxPoints() *float64 {
	if p == nil {
		return nil
	}
	return p.MaxPoints
}

func (p *PointsSystemResponse) GetTriggers() []*PointsTrigger {
	if p == nil {
		return nil
	}
	return p.Triggers
}

func (p *PointsSystemResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PointsSystemResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PointsSystemResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PointsSystemResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PointsSystemResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
