// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/trophyso/trophy-go/internal"
)

type StreaksRankingsRequest struct {
	// Number of users to return. Must be between 1 and 100.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Whether to rank users by active streaks or longest streaks ever achieved.
	Type *StreaksRankingsRequestType `json:"-" url:"type,omitempty"`
}

// A user with their streak length in the rankings.
type StreakRankingUser struct {
	// The ID of the user.
	UserId string `json:"userId" url:"userId"`
	// The name of the user. May be null if no name is set.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The user's streak length (active or longest depending on query parameter).
	StreakLength int `json:"streakLength" url:"streakLength"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *StreakRankingUser) GetUserId() string {
	if s == nil {
		return ""
	}
	return s.UserId
}

func (s *StreakRankingUser) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *StreakRankingUser) GetStreakLength() int {
	if s == nil {
		return 0
	}
	return s.StreakLength
}

func (s *StreakRankingUser) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *StreakRankingUser) UnmarshalJSON(data []byte) error {
	type unmarshaler StreakRankingUser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = StreakRankingUser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *StreakRankingUser) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type StreaksRankingsRequestType string

const (
	StreaksRankingsRequestTypeActive  StreaksRankingsRequestType = "active"
	StreaksRankingsRequestTypeLongest StreaksRankingsRequestType = "longest"
)

func NewStreaksRankingsRequestTypeFromString(s string) (StreaksRankingsRequestType, error) {
	switch s {
	case "active":
		return StreaksRankingsRequestTypeActive, nil
	case "longest":
		return StreaksRankingsRequestTypeLongest, nil
	}
	var t StreaksRankingsRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s StreaksRankingsRequestType) Ptr() *StreaksRankingsRequestType {
	return &s
}
