// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersStreaksListRequest(t *testing.T) {
	t.Run("SetUserIds", func(t *testing.T) {
		obj := &StreaksListRequest{}
		var fernTestValueUserIds []*string
		obj.SetUserIds(fernTestValueUserIds)
		assert.Equal(t, fernTestValueUserIds, obj.UserIds)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitStreaksListRequest(t *testing.T) {
	t.Run("SetUserIds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StreaksListRequest{}
		var fernTestValueUserIds []*string

		// Act
		obj.SetUserIds(fernTestValueUserIds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersBulkStreakResponseItem(t *testing.T) {
	t.Run("SetUserId", func(t *testing.T) {
		obj := &BulkStreakResponseItem{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStreakLength", func(t *testing.T) {
		obj := &BulkStreakResponseItem{}
		var fernTestValueStreakLength int
		obj.SetStreakLength(fernTestValueStreakLength)
		assert.Equal(t, fernTestValueStreakLength, obj.StreakLength)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExtended", func(t *testing.T) {
		obj := &BulkStreakResponseItem{}
		var fernTestValueExtended *string
		obj.SetExtended(fernTestValueExtended)
		assert.Equal(t, fernTestValueExtended, obj.Extended)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersBulkStreakResponseItem(t *testing.T) {
	t.Run("GetUserId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		var expected string
		obj.UserId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserId(), "getter should return the property value")
	})

	t.Run("GetUserId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BulkStreakResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserId() // Should return zero value
	})

	t.Run("GetStreakLength", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		var expected int
		obj.StreakLength = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStreakLength(), "getter should return the property value")
	})

	t.Run("GetStreakLength_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BulkStreakResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStreakLength() // Should return zero value
	})

	t.Run("GetExtended", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		var expected *string
		obj.Extended = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExtended(), "getter should return the property value")
	})

	t.Run("GetExtended_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		obj.Extended = nil

		// Act & Assert
		assert.Nil(t, obj.GetExtended(), "getter should return nil when property is nil")
	})

	t.Run("GetExtended_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BulkStreakResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExtended() // Should return zero value
	})

}

func TestSettersMarkExplicitBulkStreakResponseItem(t *testing.T) {
	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStreakLength_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		var fernTestValueStreakLength int

		// Act
		obj.SetStreakLength(fernTestValueStreakLength)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExtended_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}
		var fernTestValueExtended *string

		// Act
		obj.SetExtended(fernTestValueExtended)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingBulkStreakResponseItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BulkStreakResponseItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled BulkStreakResponseItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj BulkStreakResponseItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj BulkStreakResponseItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringBulkStreakResponseItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &BulkStreakResponseItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BulkStreakResponseItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesBulkStreakResponseItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &BulkStreakResponseItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BulkStreakResponseItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
