// Code generated by Fern. DO NOT EDIT.

package admin_tenants_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    require "github.com/stretchr/testify/require"
    trophygo "github.com/trophyso/trophy-go"
    admin "github.com/trophyso/trophy-go/admin"
    client "github.com/trophyso/trophy-go/client"
    option "github.com/trophyso/trophy-go/option"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestAdminTenantsListWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &admin.TenantsListRequest{
            Limit: trophygo.Int(
                1,
            ),
            Skip: trophygo.Int(
                1,
            ),
        }
    _, invocationErr :=     client.Admin.Tenants.List(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminTenantsListWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminTenantsListWithWireMock", "GET", "/tenants", map[string]interface{}{"limit": "1", "skip": "1"}, 1)
}

func TestAdminTenantsCreateWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := []*trophygo.CreateTenantRequestItem{
            &trophygo.CreateTenantRequestItem{
                CustomerId: "customer_12345",
                Name: "Acme Corp",
            },
            &trophygo.CreateTenantRequestItem{
                CustomerId: "customer_67890",
                Name: "Globex Inc",
            },
        }
    _, invocationErr :=     client.Admin.Tenants.Create(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminTenantsCreateWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminTenantsCreateWithWireMock", "POST", "/tenants", nil, 1)
}

func TestAdminTenantsDeleteWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &admin.TenantsDeleteRequest{
            Ids: []*string{
                trophygo.String(
                    "550e8400-e29b-41d4-a716-446655440000",
                ),
                trophygo.String(
                    "550e8400-e29b-41d4-a716-446655440001",
                ),
            },
        }
    _, invocationErr :=     client.Admin.Tenants.Delete(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminTenantsDeleteWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminTenantsDeleteWithWireMock", "DELETE", "/tenants", map[string]interface{}{"ids": []string{"550e8400-e29b-41d4-a716-446655440000", "550e8400-e29b-41d4-a716-446655440001"}}, 1)
}

func TestAdminTenantsUpdateWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := []*trophygo.UpdateTenantRequestItem{
            &trophygo.UpdateTenantRequestItem{
                Id: "550e8400-e29b-41d4-a716-446655440000",
                Name: trophygo.String(
                    "Acme Corporation",
                ),
            },
        }
    _, invocationErr :=     client.Admin.Tenants.Update(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminTenantsUpdateWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminTenantsUpdateWithWireMock", "PATCH", "/tenants", nil, 1)
}

func TestAdminTenantsGetWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
    _, invocationErr :=     client.Admin.Tenants.Get(
            context.TODO(),
            "550e8400-e29b-41d4-a716-446655440000",
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminTenantsGetWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminTenantsGetWithWireMock", "GET", "/tenants/550e8400-e29b-41d4-a716-446655440000", nil, 1)
}


