// Code generated by Fern. DO NOT EDIT.

package client

import (
    achievements "github.com/trophyso/trophy-go/admin/achievements"
    applicationapikeys "github.com/trophyso/trophy-go/admin/applicationapikeys"
    attributes "github.com/trophyso/trophy-go/admin/attributes"
    environments "github.com/trophyso/trophy-go/admin/environments"
    leaderboards "github.com/trophyso/trophy-go/admin/leaderboards"
    metrics "github.com/trophyso/trophy-go/admin/metrics"
    pointsclient "github.com/trophyso/trophy-go/admin/points/client"
    settings "github.com/trophyso/trophy-go/admin/settings"
    client "github.com/trophyso/trophy-go/admin/streaks/client"
    tenants "github.com/trophyso/trophy-go/admin/tenants"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
)


type Client struct {
    Attributes *attributes.Client
    Achievements *achievements.Client
    Metrics *metrics.Client
    Leaderboards *leaderboards.Client
    Streaks *client.Client
    Settings *settings.Client
    ApplicationApiKeys *applicationapikeys.Client
    Environments *environments.Client
    Tenants *tenants.Client
    Points *pointsclient.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.26.0"
    }
    return &Client{
        Attributes: attributes.NewClient(options),
        Achievements: achievements.NewClient(options),
        Metrics: metrics.NewClient(options),
        Leaderboards: leaderboards.NewClient(options),
        Streaks: client.NewClient(options),
        Settings: settings.NewClient(options),
        ApplicationApiKeys: applicationapikeys.NewClient(options),
        Environments: environments.NewClient(options),
        Tenants: tenants.NewClient(options),
        Points: pointsclient.NewClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

