// This file was auto-generated by Fern from our API Definition.

package client

import (
	attributes "github.com/trophyso/trophy-go/admin/attributes"
	metrics "github.com/trophyso/trophy-go/admin/metrics"
	pointsclient "github.com/trophyso/trophy-go/admin/points/client"
	streaksclient "github.com/trophyso/trophy-go/admin/streaks/client"
	core "github.com/trophyso/trophy-go/core"
	internal "github.com/trophyso/trophy-go/internal"
	option "github.com/trophyso/trophy-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Streaks    *streaksclient.Client
	Attributes *attributes.Client
	Metrics    *metrics.Client
	Points     *pointsclient.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:     options.ToHeader(),
		Streaks:    streaksclient.NewClient(opts...),
		Attributes: attributes.NewClient(opts...),
		Metrics:    metrics.NewClient(opts...),
		Points:     pointsclient.NewClient(opts...),
	}
}
