// Code generated by Fern. DO NOT EDIT.

package client

import (
    boosts "github.com/trophyso/trophy-go/admin/points/boosts"
    levels "github.com/trophyso/trophy-go/admin/points/levels"
    systems "github.com/trophyso/trophy-go/admin/points/systems"
    triggers "github.com/trophyso/trophy-go/admin/points/triggers"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
)


type Client struct {
    Systems *systems.Client
    Boosts *boosts.Client
    Levels *levels.Client
    Triggers *triggers.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.15.0"
    }
    return &Client{
        Systems: systems.NewClient(options),
        Boosts: boosts.NewClient(options),
        Levels: levels.NewClient(options),
        Triggers: triggers.NewClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

