// Code generated by Fern. DO NOT EDIT.

package client

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    admin "github.com/trophyso/trophy-go/admin"
    freezes "github.com/trophyso/trophy-go/admin/streaks/freezes"
    pauses "github.com/trophyso/trophy-go/admin/streaks/pauses"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient
    Freezes *freezes.Client
    Pauses *pauses.Client

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.23.0"
    }
    return &Client{
        Freezes: freezes.NewClient(options),
        Pauses: pauses.NewClient(options),
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Restore streaks for multiple users to the maximum previously achieved streak length found within the current restore window: the last 90 days for daily streaks, weekly periods starting with the week containing the start of the current calendar year for weekly streaks, and monthly periods starting at the beginning of the previous calendar year for monthly streaks.
func (c *Client) Restore(
    ctx context.Context,
    request *admin.RestoreStreaksRequest,
    opts ...option.RequestOption,
) (*trophygo.RestoreStreaksResponse, error){
    response, err := c.WithRawResponse.Restore(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

