// Code generated by Fern. DO NOT EDIT.

package points

import (
	big "math/big"
)

var (
	boostsDeleteRequestFieldIds = big.NewInt(1 << 0)
)

type BoostsDeleteRequest struct {
	// A list of up to 100 boost IDs.
	Ids []*string `json:"-" url:"ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BoostsDeleteRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoostsDeleteRequest) SetIds(ids []*string) {
	b.Ids = ids
	b.require(boostsDeleteRequestFieldIds)
}

var (
	boostsListRequestFieldLimit = big.NewInt(1 << 0)
	boostsListRequestFieldSkip  = big.NewInt(1 << 1)
)

type BoostsListRequest struct {
	// Maximum number of results to return (1-100, default 10).
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of results to skip for pagination (default 0).
	Skip *int `json:"-" url:"skip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BoostsListRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoostsListRequest) SetLimit(limit *int) {
	b.Limit = limit
	b.require(boostsListRequestFieldLimit)
}

// SetSkip sets the Skip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoostsListRequest) SetSkip(skip *int) {
	b.Skip = skip
	b.require(boostsListRequestFieldSkip)
}
