// Code generated by Fern. DO NOT EDIT.

package points

import (
	big "math/big"
)

var (
	levelsDeleteRequestFieldIds = big.NewInt(1 << 0)
)

type LevelsDeleteRequest struct {
	// Comma-separated list of level UUIDs to delete.
	Ids []*string `json:"-" url:"ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LevelsDeleteRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LevelsDeleteRequest) SetIds(ids []*string) {
	l.Ids = ids
	l.require(levelsDeleteRequestFieldIds)
}

var (
	levelsListRequestFieldLimit = big.NewInt(1 << 0)
	levelsListRequestFieldSkip  = big.NewInt(1 << 1)
)

type LevelsListRequest struct {
	// Number of records to return.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of records to skip from the start of the list.
	Skip *int `json:"-" url:"skip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LevelsListRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LevelsListRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(levelsListRequestFieldLimit)
}

// SetSkip sets the Skip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LevelsListRequest) SetSkip(skip *int) {
	l.Skip = skip
	l.require(levelsListRequestFieldSkip)
}
