// Code generated by Fern. DO NOT EDIT.

package points

import (
	big "math/big"
)

var (
	systemsDeleteRequestFieldIds = big.NewInt(1 << 0)
)

type SystemsDeleteRequest struct {
	// The IDs of the points systems to delete.
	Ids []*string `json:"-" url:"ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SystemsDeleteRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SystemsDeleteRequest) SetIds(ids []*string) {
	s.Ids = ids
	s.require(systemsDeleteRequestFieldIds)
}

var (
	systemsListRequestFieldLimit = big.NewInt(1 << 0)
	systemsListRequestFieldSkip  = big.NewInt(1 << 1)
)

type SystemsListRequest struct {
	// Number of records to return.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of records to skip from the start of the list.
	Skip *int `json:"-" url:"skip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SystemsListRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SystemsListRequest) SetLimit(limit *int) {
	s.Limit = limit
	s.require(systemsListRequestFieldLimit)
}

// SetSkip sets the Skip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SystemsListRequest) SetSkip(skip *int) {
	s.Skip = skip
	s.require(systemsListRequestFieldSkip)
}
