// This file was auto-generated by Fern from our API Definition.

package points

type TriggersDeleteRequest struct {
	// Trigger IDs to delete. Can be repeated or comma-separated.
	Ids []*string `json:"-" url:"ids,omitempty"`
}

type TriggersListRequest struct {
	// Maximum number of results to return (1-100, default 10).
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of results to skip for pagination (default 0).
	Skip *int `json:"-" url:"skip,omitempty"`
}
