// Code generated by Fern. DO NOT EDIT.

package points

import (
	big "math/big"
)

var (
	triggersDeleteRequestFieldIds = big.NewInt(1 << 0)
)

type TriggersDeleteRequest struct {
	// Trigger IDs to delete. Can be repeated or comma-separated.
	Ids []*string `json:"-" url:"ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TriggersDeleteRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TriggersDeleteRequest) SetIds(ids []*string) {
	t.Ids = ids
	t.require(triggersDeleteRequestFieldIds)
}

var (
	triggersListRequestFieldLimit = big.NewInt(1 << 0)
	triggersListRequestFieldSkip  = big.NewInt(1 << 1)
)

type TriggersListRequest struct {
	// Maximum number of results to return (1-100, default 10).
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of results to skip for pagination (default 0).
	Skip *int `json:"-" url:"skip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TriggersListRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TriggersListRequest) SetLimit(limit *int) {
	t.Limit = limit
	t.require(triggersListRequestFieldLimit)
}

// SetSkip sets the Skip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TriggersListRequest) SetSkip(skip *int) {
	t.Skip = skip
	t.require(triggersListRequestFieldSkip)
}
