// This file was auto-generated by Fern from our API Definition.

package streaks

import (
	context "context"
	trophygo "github.com/trophyso/trophy-go"
	core "github.com/trophyso/trophy-go/core"
	internal "github.com/trophyso/trophy-go/internal"
	option "github.com/trophyso/trophy-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Get the top users by streak length (active or longest).
func (c *Client) Rankings(
	ctx context.Context,
	request *trophygo.StreaksRankingsRequest,
	opts ...option.RequestOption,
) ([]*trophygo.StreakRankingUser, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://app.trophy.so/api",
	)
	endpointURL := baseURL + "/streaks/rankings"
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response []*trophygo.StreakRankingUser
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
