// Code generated by Fern. DO NOT EDIT.

package leaderboards

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.19.0"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Get all leaderboards for your organization. Finished leaderboards are excluded by default.
func (c *Client) All(
    ctx context.Context,
    request *trophygo.LeaderboardsAllRequest,
    opts ...option.RequestOption,
) ([]*trophygo.LeaderboardsAllResponseItem, error){
    response, err := c.WithRawResponse.All(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a specific leaderboard by its key.
func (c *Client) Get(
    ctx context.Context,
    // Unique key of the leaderboard as set when created.
    key string,
    request *trophygo.LeaderboardsGetRequest,
    opts ...option.RequestOption,
) (*trophygo.LeaderboardResponseWithRankings, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        key,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

