// Code generated by Fern. DO NOT EDIT.

package admin

import (
	big "math/big"
)

var (
	achievementsDeleteRequestFieldIds = big.NewInt(1 << 0)
)

type AchievementsDeleteRequest struct {
	// Achievement IDs to delete. Repeat the query param or provide a comma-separated list.
	Ids []*string `json:"-" url:"ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AchievementsDeleteRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AchievementsDeleteRequest) SetIds(ids []*string) {
	a.Ids = ids
	a.require(achievementsDeleteRequestFieldIds)
}

var (
	achievementsListRequestFieldLimit = big.NewInt(1 << 0)
	achievementsListRequestFieldSkip  = big.NewInt(1 << 1)
)

type AchievementsListRequest struct {
	// Number of records to return.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of records to skip from the start of the list.
	Skip *int `json:"-" url:"skip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AchievementsListRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AchievementsListRequest) SetLimit(limit *int) {
	a.Limit = limit
	a.require(achievementsListRequestFieldLimit)
}

// SetSkip sets the Skip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AchievementsListRequest) SetSkip(skip *int) {
	a.Skip = skip
	a.require(achievementsListRequestFieldSkip)
}
