// Code generated by Fern. DO NOT EDIT.

package admin

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersApplicationApiKeysDeleteRequest(t *testing.T) {
	t.Run("SetIds", func(t *testing.T) {
		obj := &ApplicationApiKeysDeleteRequest{}
		var fernTestValueIds []*string
		obj.SetIds(fernTestValueIds)
		assert.Equal(t, fernTestValueIds, obj.Ids)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitApplicationApiKeysDeleteRequest(t *testing.T) {
	t.Run("SetIds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ApplicationApiKeysDeleteRequest{}
		var fernTestValueIds []*string

		// Act
		obj.SetIds(fernTestValueIds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}
