// Code generated by Fern. DO NOT EDIT.

package admin

import (
    trophygo "github.com/trophyso/trophy-go"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
)


var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
    401: func(apiError *core.APIError) error{
        return &trophygo.UnauthorizedError{
            APIError: apiError,
        }
    },
    422: func(apiError *core.APIError) error{
        return &trophygo.UnprocessableEntityError{
            APIError: apiError,
        }
    },
    404: func(apiError *core.APIError) error{
        return &trophygo.NotFoundError{
            APIError: apiError,
        }
    },
    400: func(apiError *core.APIError) error{
        return &trophygo.BadRequestError{
            APIError: apiError,
        }
    },
    403: func(apiError *core.APIError) error{
        return &trophygo.ForbiddenError{
            APIError: apiError,
        }
    },
}

