// Code generated by Fern. DO NOT EDIT.

package admin

import (
	big "math/big"
)

var (
	leaderboardsDeleteRequestFieldIds = big.NewInt(1 << 0)
)

type LeaderboardsDeleteRequest struct {
	// Leaderboard IDs to delete. Repeat the query param or provide a comma-separated list.
	Ids []*string `json:"-" url:"ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LeaderboardsDeleteRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsDeleteRequest) SetIds(ids []*string) {
	l.Ids = ids
	l.require(leaderboardsDeleteRequestFieldIds)
}

var (
	leaderboardsListRequestFieldLimit = big.NewInt(1 << 0)
	leaderboardsListRequestFieldSkip  = big.NewInt(1 << 1)
)

type LeaderboardsListRequest struct {
	// Number of records to return.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of records to skip from the start of the list.
	Skip *int `json:"-" url:"skip,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LeaderboardsListRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsListRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(leaderboardsListRequestFieldLimit)
}

// SetSkip sets the Skip field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LeaderboardsListRequest) SetSkip(skip *int) {
	l.Skip = skip
	l.require(leaderboardsListRequestFieldSkip)
}
