// Code generated by Fern. DO NOT EDIT.

package admin

import (
	json "encoding/json"
	trophygo "github.com/trophyso/trophy-go"
	internal "github.com/trophyso/trophy-go/internal"
	big "math/big"
)

var (
	updateAdminSettingsRequestFieldBranding          = big.NewInt(1 << 0)
	updateAdminSettingsRequestFieldExperimentation   = big.NewInt(1 << 1)
	updateAdminSettingsRequestFieldAggregationPeriod = big.NewInt(1 << 2)
)

type UpdateAdminSettingsRequest struct {
	Branding          *trophygo.UpdateAdminSettingsBranding        `json:"branding,omitempty" url:"-"`
	Experimentation   *trophygo.UpdateAdminSettingsExperimentation `json:"experimentation,omitempty" url:"-"`
	AggregationPeriod *trophygo.AdminAggregationPeriod             `json:"aggregationPeriod,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateAdminSettingsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetBranding sets the Branding field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAdminSettingsRequest) SetBranding(branding *trophygo.UpdateAdminSettingsBranding) {
	u.Branding = branding
	u.require(updateAdminSettingsRequestFieldBranding)
}

// SetExperimentation sets the Experimentation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAdminSettingsRequest) SetExperimentation(experimentation *trophygo.UpdateAdminSettingsExperimentation) {
	u.Experimentation = experimentation
	u.require(updateAdminSettingsRequestFieldExperimentation)
}

// SetAggregationPeriod sets the AggregationPeriod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateAdminSettingsRequest) SetAggregationPeriod(aggregationPeriod *trophygo.AdminAggregationPeriod) {
	u.AggregationPeriod = aggregationPeriod
	u.require(updateAdminSettingsRequestFieldAggregationPeriod)
}

func (u *UpdateAdminSettingsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateAdminSettingsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateAdminSettingsRequest(body)
	return nil
}

func (u *UpdateAdminSettingsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateAdminSettingsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
