// This file was auto-generated by Fern from our API Definition.

package admin

type RestoreStreaksRequest struct {
	// Array of user IDs to restore streaks for. Maximum 100 users per request.
	UserIds []string `json:"userIds,omitempty" url:"-"`
}
