// This file was auto-generated by Fern from our API Definition.

package admin

type TenantsDeleteRequest struct {
	// Tenant IDs to delete. Repeat the query param or provide a comma-separated list.
	Ids []*string `json:"-" url:"ids,omitempty"`
}

type TenantsListRequest struct {
	// Number of records to return.
	Limit *int `json:"-" url:"limit,omitempty"`
	// Number of records to skip from the start of the list.
	Skip *int `json:"-" url:"skip,omitempty"`
}
