// Code generated by Fern. DO NOT EDIT.

package streaks

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/trophyso/trophy-go/internal"
	big "math/big"
)

var (
	createStreakFreezesRequestFieldFreezes = big.NewInt(1 << 0)
)

type CreateStreakFreezesRequest struct {
	// Array of freezes to create. Maximum 100 freezes per request.
	Freezes []*CreateStreakFreezesRequestFreezesItem `json:"freezes" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateStreakFreezesRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFreezes sets the Freezes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateStreakFreezesRequest) SetFreezes(freezes []*CreateStreakFreezesRequestFreezesItem) {
	c.Freezes = freezes
	c.require(createStreakFreezesRequestFieldFreezes)
}

func (c *CreateStreakFreezesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateStreakFreezesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateStreakFreezesRequest(body)
	return nil
}

func (c *CreateStreakFreezesRequest) MarshalJSON() ([]byte, error) {
	type embed CreateStreakFreezesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createStreakFreezesRequestFreezesItemFieldUserId = big.NewInt(1 << 0)
)

type CreateStreakFreezesRequestFreezesItem struct {
	// The ID of the user to create a freeze for.
	UserId string `json:"userId" url:"userId"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateStreakFreezesRequestFreezesItem) GetUserId() string {
	if c == nil {
		return ""
	}
	return c.UserId
}

func (c *CreateStreakFreezesRequestFreezesItem) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateStreakFreezesRequestFreezesItem) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateStreakFreezesRequestFreezesItem) SetUserId(userId string) {
	c.UserId = userId
	c.require(createStreakFreezesRequestFreezesItemFieldUserId)
}

func (c *CreateStreakFreezesRequestFreezesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateStreakFreezesRequestFreezesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateStreakFreezesRequestFreezesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateStreakFreezesRequestFreezesItem) MarshalJSON() ([]byte, error) {
	type embed CreateStreakFreezesRequestFreezesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateStreakFreezesRequestFreezesItem) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
