// This file was auto-generated by Fern from our API Definition.

package streaks

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/trophyso/trophy-go/internal"
)

type CreateStreakFreezesRequest struct {
	// Array of freezes to create. Maximum 1,000 freezes per request.
	Freezes []*CreateStreakFreezesRequestFreezesItem `json:"freezes,omitempty" url:"-"`
}

type CreateStreakFreezesRequestFreezesItem struct {
	// The ID of the user to create a freeze for.
	UserId string `json:"userId" url:"userId"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateStreakFreezesRequestFreezesItem) GetUserId() string {
	if c == nil {
		return ""
	}
	return c.UserId
}

func (c *CreateStreakFreezesRequestFreezesItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateStreakFreezesRequestFreezesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateStreakFreezesRequestFreezesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateStreakFreezesRequestFreezesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateStreakFreezesRequestFreezesItem) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
