// Code generated by Fern. DO NOT EDIT.

package streaks

import (
	json "encoding/json"
	trophygo "github.com/trophyso/trophy-go"
	internal "github.com/trophyso/trophy-go/internal"
	big "math/big"
)

var (
	updateStreakSettingsRequestFieldFrequency            = big.NewInt(1 << 0)
	updateStreakSettingsRequestFieldEvaluationMode       = big.NewInt(1 << 1)
	updateStreakSettingsRequestFieldCustomizationEnabled = big.NewInt(1 << 2)
	updateStreakSettingsRequestFieldDaysOff              = big.NewInt(1 << 3)
	updateStreakSettingsRequestFieldMetrics              = big.NewInt(1 << 4)
	updateStreakSettingsRequestFieldFreezes              = big.NewInt(1 << 5)
)

type UpdateStreakSettingsRequest struct {
	Frequency      *trophygo.AdminStreakFrequency      `json:"frequency,omitempty" url:"-"`
	EvaluationMode *trophygo.AdminStreakEvaluationMode `json:"evaluationMode,omitempty" url:"-"`
	// Whether users can override streak evaluation mode, metric thresholds, and days off via preferences.
	CustomizationEnabled *bool `json:"customizationEnabled,omitempty" url:"-"`
	// Days of the week that do not count toward the daily streak. A non-empty array is only allowed when the resulting frequency is `daily`. Changing frequency away from `daily` clears stored days off even when this field is omitted.
	DaysOff []int `json:"daysOff,omitempty" url:"-"`
	// Replacement list of streak metrics. Keys must be unique and must exist on the organization.
	Metrics []*trophygo.StreakSettingsMetric `json:"metrics,omitempty" url:"-"`
	// Replacement freeze configuration, or `null` to disable freezes.
	Freezes *trophygo.UpdateStreakSettingsFreezes `json:"freezes,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateStreakSettingsRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetFrequency sets the Frequency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateStreakSettingsRequest) SetFrequency(frequency *trophygo.AdminStreakFrequency) {
	u.Frequency = frequency
	u.require(updateStreakSettingsRequestFieldFrequency)
}

// SetEvaluationMode sets the EvaluationMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateStreakSettingsRequest) SetEvaluationMode(evaluationMode *trophygo.AdminStreakEvaluationMode) {
	u.EvaluationMode = evaluationMode
	u.require(updateStreakSettingsRequestFieldEvaluationMode)
}

// SetCustomizationEnabled sets the CustomizationEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateStreakSettingsRequest) SetCustomizationEnabled(customizationEnabled *bool) {
	u.CustomizationEnabled = customizationEnabled
	u.require(updateStreakSettingsRequestFieldCustomizationEnabled)
}

// SetDaysOff sets the DaysOff field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateStreakSettingsRequest) SetDaysOff(daysOff []int) {
	u.DaysOff = daysOff
	u.require(updateStreakSettingsRequestFieldDaysOff)
}

// SetMetrics sets the Metrics field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateStreakSettingsRequest) SetMetrics(metrics []*trophygo.StreakSettingsMetric) {
	u.Metrics = metrics
	u.require(updateStreakSettingsRequestFieldMetrics)
}

// SetFreezes sets the Freezes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateStreakSettingsRequest) SetFreezes(freezes *trophygo.UpdateStreakSettingsFreezes) {
	u.Freezes = freezes
	u.require(updateStreakSettingsRequestFieldFreezes)
}

func (u *UpdateStreakSettingsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateStreakSettingsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateStreakSettingsRequest(body)
	return nil
}

func (u *UpdateStreakSettingsRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateStreakSettingsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
