// Code generated by Fern. DO NOT EDIT.

package admin_points_boosts_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    require "github.com/stretchr/testify/require"
    trophygo "github.com/trophyso/trophy-go"
    points "github.com/trophyso/trophy-go/admin/points"
    client "github.com/trophyso/trophy-go/client"
    option "github.com/trophyso/trophy-go/option"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestAdminPointsBoostsListWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &points.BoostsListRequest{
            Limit: trophygo.Int(
                1,
            ),
            Skip: trophygo.Int(
                1,
            ),
        }
    _, invocationErr :=     client.Admin.Points.Boosts.List(
            context.TODO(),
            "550e8400-e29b-41d4-a716-446655440000",
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminPointsBoostsListWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminPointsBoostsListWithWireMock", "GET", "/points/550e8400-e29b-41d4-a716-446655440000/boosts", map[string]interface{}{"limit": "1", "skip": "1"}, 1)
}

func TestAdminPointsBoostsCreateWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := []*trophygo.CreatePointsBoostRequestItem{
            &trophygo.CreatePointsBoostRequestItem{
                UserId: trophygo.String(
                    "user-123",
                ),
                Name: "Double XP Weekend",
                Start: "2024-01-01",
                End: trophygo.String(
                    "2024-01-03",
                ),
                Multiplier: 2,
            },
        }
    _, invocationErr :=     client.Admin.Points.Boosts.Create(
            context.TODO(),
            "550e8400-e29b-41d4-a716-446655440000",
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminPointsBoostsCreateWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminPointsBoostsCreateWithWireMock", "POST", "/points/550e8400-e29b-41d4-a716-446655440000/boosts", nil, 1)
}

func TestAdminPointsBoostsDeleteWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &points.BoostsDeleteRequest{
            Ids: []*string{
                trophygo.String(
                    "ids",
                ),
            },
        }
    _, invocationErr :=     client.Admin.Points.Boosts.Delete(
            context.TODO(),
            "550e8400-e29b-41d4-a716-446655440000",
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminPointsBoostsDeleteWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminPointsBoostsDeleteWithWireMock", "DELETE", "/points/550e8400-e29b-41d4-a716-446655440000/boosts", map[string]interface{}{"ids": "ids"}, 1)
}

func TestAdminPointsBoostsUpdateWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := []*trophygo.PatchPointsBoostsRequestItem{
            &trophygo.PatchPointsBoostsRequestItem{
                Id: "550e8400-e29b-41d4-a716-446655440000",
                Name: trophygo.String(
                    "Updated Boost Name",
                ),
                Multiplier: trophygo.Float64(
                    3,
                ),
            },
        }
    _, invocationErr :=     client.Admin.Points.Boosts.Update(
            context.TODO(),
            "550e8400-e29b-41d4-a716-446655440000",
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminPointsBoostsUpdateWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminPointsBoostsUpdateWithWireMock", "PATCH", "/points/550e8400-e29b-41d4-a716-446655440000/boosts", nil, 1)
}

func TestAdminPointsBoostsGetWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
    _, invocationErr :=     client.Admin.Points.Boosts.Get(
            context.TODO(),
            "550e8400-e29b-41d4-a716-446655440000",
            "660f9500-f30c-42e5-b827-557766550001",
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestAdminPointsBoostsGetWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestAdminPointsBoostsGetWithWireMock", "GET", "/points/550e8400-e29b-41d4-a716-446655440000/boosts/660f9500-f30c-42e5-b827-557766550001", nil, 1)
}


