// Code generated by Fern. DO NOT EDIT.

package users

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.20.1"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Create a new user.
func (c *Client) Create(
    ctx context.Context,
    request *trophygo.UpsertedUser,
    opts ...option.RequestOption,
) (*trophygo.User, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a single user.
func (c *Client) Get(
    ctx context.Context,
    // ID of the user to get.
    id string,
    opts ...option.RequestOption,
) (*trophygo.User, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        id,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Identify a user.
func (c *Client) Identify(
    ctx context.Context,
    // ID of the user to identify.
    id string,
    request *trophygo.UpdatedUser,
    opts ...option.RequestOption,
) (*trophygo.User, error){
    response, err := c.WithRawResponse.Identify(
        ctx,
        id,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Update a user.
func (c *Client) Update(
    ctx context.Context,
    // ID of the user to update.
    id string,
    request *trophygo.UpdatedUser,
    opts ...option.RequestOption,
) (*trophygo.User, error){
    response, err := c.WithRawResponse.Update(
        ctx,
        id,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's notification preferences.
func (c *Client) GetPreferences(
    ctx context.Context,
    // The user's ID in your database.
    id string,
    opts ...option.RequestOption,
) (*trophygo.UserPreferencesResponse, error){
    response, err := c.WithRawResponse.GetPreferences(
        ctx,
        id,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Update a user's notification and streak preferences. Streak preferences require streak customization to be enabled in your Trophy dashboard settings.
func (c *Client) UpdatePreferences(
    ctx context.Context,
    // The user's ID in your database.
    id string,
    request *trophygo.UpdateUserPreferencesRequest,
    opts ...option.RequestOption,
) (*trophygo.UserPreferencesResponse, error){
    response, err := c.WithRawResponse.UpdatePreferences(
        ctx,
        id,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a single user's progress against all active metrics.
func (c *Client) AllMetrics(
    ctx context.Context,
    // ID of the user
    id string,
    opts ...option.RequestOption,
) ([]*trophygo.MetricResponse, error){
    response, err := c.WithRawResponse.AllMetrics(
        ctx,
        id,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's progress against a single active metric.
func (c *Client) SingleMetric(
    ctx context.Context,
    // ID of the user.
    id string,
    // Unique key of the metric.
    key string,
    opts ...option.RequestOption,
) (*trophygo.MetricResponse, error){
    response, err := c.WithRawResponse.SingleMetric(
        ctx,
        id,
        key,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a summary of metric events over time for a user.
func (c *Client) MetricEventSummary(
    ctx context.Context,
    // ID of the user.
    id string,
    // Unique key of the metric.
    key string,
    request *trophygo.UsersMetricEventSummaryRequest,
    opts ...option.RequestOption,
) ([]*trophygo.UsersMetricEventSummaryResponseItem, error){
    response, err := c.WithRawResponse.MetricEventSummary(
        ctx,
        id,
        key,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's achievements.
func (c *Client) Achievements(
    ctx context.Context,
    // ID of the user.
    id string,
    request *trophygo.UsersAchievementsRequest,
    opts ...option.RequestOption,
) ([]*trophygo.UserAchievementWithStatsResponse, error){
    response, err := c.WithRawResponse.Achievements(
        ctx,
        id,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's streak data.
func (c *Client) Streak(
    ctx context.Context,
    // ID of the user.
    id string,
    request *trophygo.UsersStreakRequest,
    opts ...option.RequestOption,
) (*trophygo.StreakResponse, error){
    response, err := c.WithRawResponse.Streak(
        ctx,
        id,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's points for a specific points system.
func (c *Client) Points(
    ctx context.Context,
    // ID of the user.
    id string,
    // Key of the points system.
    key string,
    request *trophygo.UsersPointsRequest,
    opts ...option.RequestOption,
) (*trophygo.GetUserPointsResponse, error){
    response, err := c.WithRawResponse.Points(
        ctx,
        id,
        key,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get active points boosts for a user in a specific points system. Returns both global boosts the user is eligible for and user-specific boosts.
func (c *Client) PointsBoosts(
    ctx context.Context,
    // ID of the user.
    id string,
    // Key of the points system.
    key string,
    opts ...option.RequestOption,
) ([]*trophygo.PointsBoost, error){
    response, err := c.WithRawResponse.PointsBoosts(
        ctx,
        id,
        key,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a summary of points awards over time for a user for a specific points system.
func (c *Client) PointsEventSummary(
    ctx context.Context,
    // ID of the user.
    id string,
    // Key of the points system.
    key string,
    request *trophygo.UsersPointsEventSummaryRequest,
    opts ...option.RequestOption,
) ([]*trophygo.UsersPointsEventSummaryResponseItem, error){
    response, err := c.WithRawResponse.PointsEventSummary(
        ctx,
        id,
        key,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's rank, value, and daily ranking history for a specific leaderboard.
func (c *Client) Leaderboard(
    ctx context.Context,
    // The user's ID in your database.
    id string,
    // Unique key of the leaderboard as set when created.
    key string,
    request *trophygo.UsersLeaderboardRequest,
    opts ...option.RequestOption,
) (*trophygo.UserLeaderboardResponseWithHistory, error){
    response, err := c.WithRawResponse.Leaderboard(
        ctx,
        id,
        key,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a user's year-in-review wrapped data.
func (c *Client) Wrapped(
    ctx context.Context,
    // The user's ID in your database.
    id string,
    request *trophygo.UsersWrappedRequest,
    opts ...option.RequestOption,
) (*trophygo.WrappedResponse, error){
    response, err := c.WithRawResponse.Wrapped(
        ctx,
        id,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

