// Code generated by Fern. DO NOT EDIT.

package leaderboards_test

import (
    bytes "bytes"
    context "context"
    json "encoding/json"
    http "net/http"
    os "os"
    testing "testing"

    require "github.com/stretchr/testify/require"
    trophygo "github.com/trophyso/trophy-go"
    client "github.com/trophyso/trophy-go/client"
    option "github.com/trophyso/trophy-go/option"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]any,
    expected int,
) {
    wiremockURL := os.Getenv("WIREMOCK_URL")
    	if wiremockURL == "" {
    		wiremockURL = "http://localhost:8080"
    	}
    	WiremockAdminURL := wiremockURL + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            switch v := value.(type) {
            case string:
                reqBody.WriteString(`":{"equalTo":"`)
                reqBody.WriteString(v)
                reqBody.WriteString(`"}`)
            case []string:
                reqBody.WriteString(`":{"hasExactly":[`)
                for i, item := range v {
                    if i > 0 {
                        reqBody.WriteString(",")
                    }
                    reqBody.WriteString(`{"equalTo":"`)
                    reqBody.WriteString(item)
                    reqBody.WriteString(`"}`)
                }
                reqBody.WriteString(`]}`)
            }
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestLeaderboardsAllWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &trophygo.LeaderboardsAllRequest{
            IncludeFinished: trophygo.Bool(
                true,
            ),
        }
    _, invocationErr :=     client.Leaderboards.All(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestLeaderboardsAllWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestLeaderboardsAllWithWireMock", "GET", "/leaderboards", map[string]interface{}{"includeFinished": "true"}, 1)
}

func TestLeaderboardsGetWithWireMock(
    t *testing.T,
) {
    WireMockBaseURL := os.Getenv("WIREMOCK_URL")
    	if WireMockBaseURL == "" {
    		WireMockBaseURL = "http://localhost:8080"
    	}
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
        option.WithApiKey("test-value"),
    )
        request := &trophygo.LeaderboardsGetRequest{
            Offset: trophygo.Int(
                1,
            ),
            Limit: trophygo.Int(
                1,
            ),
            Run: trophygo.String(
                "2025-01-15",
            ),
            UserId: trophygo.String(
                "user-123",
            ),
            UserAttributes: trophygo.String(
                "city:London",
            ),
        }
    _, invocationErr :=     client.Leaderboards.Get(
            context.TODO(),
            "weekly-words",
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestLeaderboardsGetWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestLeaderboardsGetWithWireMock", "GET", "/leaderboards/weekly-words", map[string]interface{}{"offset": "1", "limit": "1", "run": "2025-01-15", "userId": "user-123", "userAttributes": "city:London"}, 1)
}


