// Code generated by Fern. DO NOT EDIT.

package settings

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    streaks "github.com/trophyso/trophy-go/admin/streaks"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.24.0"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Get the organization's streak configuration.
func (c *Client) Get(
    ctx context.Context,
    opts ...option.RequestOption,
) (*trophygo.StreakSettings, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Update the organization's streak configuration.
func (c *Client) Update(
    ctx context.Context,
    request *streaks.UpdateStreakSettingsRequest,
    opts ...option.RequestOption,
) (*trophygo.StreakSettings, error){
    response, err := c.WithRawResponse.Update(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

