// This file was auto-generated by Fern from our API Definition.

package levels

import (
	context "context"
	trophygo "github.com/trophyso/trophy-go"
	points "github.com/trophyso/trophy-go/admin/points"
	core "github.com/trophyso/trophy-go/core"
	internal "github.com/trophyso/trophy-go/internal"
	option "github.com/trophyso/trophy-go/option"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// List points levels for a system.
func (c *Client) List(
	ctx context.Context,
	// The UUID of the points system.
	systemId string,
	request *points.LevelsListRequest,
	opts ...option.RequestOption,
) (trophygo.ListPointsLevelsResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://admin.trophy.so/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/points/%v/levels",
		systemId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &trophygo.NotFoundError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response trophygo.ListPointsLevelsResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Create points levels. Maximum 100 levels per request.
func (c *Client) Create(
	ctx context.Context,
	// The UUID of the points system.
	systemId string,
	request trophygo.CreatePointsLevelsRequest,
	opts ...option.RequestOption,
) (*trophygo.CreatePointsLevelsResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://admin.trophy.so/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/points/%v/levels",
		systemId,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &trophygo.NotFoundError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response *trophygo.CreatePointsLevelsResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Delete multiple points levels by ID.
func (c *Client) Delete(
	ctx context.Context,
	// The UUID of the points system.
	systemId string,
	request *points.LevelsDeleteRequest,
	opts ...option.RequestOption,
) (*trophygo.DeletePointsLevelsResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://admin.trophy.so/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/points/%v/levels",
		systemId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &trophygo.NotFoundError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response *trophygo.DeletePointsLevelsResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Update multiple points levels. Each item must include an ID. `key` cannot be changed.
func (c *Client) Update(
	ctx context.Context,
	// The UUID of the points system.
	systemId string,
	request trophygo.PatchPointsLevelsRequest,
	opts ...option.RequestOption,
) (*trophygo.PatchPointsLevelsResponse, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://admin.trophy.so/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/points/%v/levels",
		systemId,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	headers.Set("Content-Type", "application/json")
	errorCodes := internal.ErrorCodes{
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &trophygo.NotFoundError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response *trophygo.PatchPointsLevelsResponse
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}

// Get a single points level by ID.
func (c *Client) Get(
	ctx context.Context,
	// The UUID of the points system.
	systemId string,
	// The UUID of the points level.
	id string,
	opts ...option.RequestOption,
) (*trophygo.AdminPointsLevel, error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		c.baseURL,
		"https://admin.trophy.so/v1",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/points/%v/levels/%v",
		systemId,
		id,
	)
	headers := internal.MergeHeaders(
		c.header.Clone(),
		options.ToHeader(),
	)
	errorCodes := internal.ErrorCodes{
		401: func(apiError *core.APIError) error {
			return &trophygo.UnauthorizedError{
				APIError: apiError,
			}
		},
		404: func(apiError *core.APIError) error {
			return &trophygo.NotFoundError{
				APIError: apiError,
			}
		},
		422: func(apiError *core.APIError) error {
			return &trophygo.UnprocessableEntityError{
				APIError: apiError,
			}
		},
	}

	var response *trophygo.AdminPointsLevel
	if err := c.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(errorCodes),
		},
	); err != nil {
		return nil, err
	}
	return response, nil
}
