// Code generated by Fern. DO NOT EDIT.

package levels

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    points "github.com/trophyso/trophy-go/admin/points"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.15.0"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// List points levels for a system.
func (c *Client) List(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request *points.LevelsListRequest,
    opts ...option.RequestOption,
) (trophygo.ListPointsLevelsResponse, error){
    response, err := c.WithRawResponse.List(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Create points levels. Maximum 100 levels per request.
func (c *Client) Create(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request trophygo.CreatePointsLevelsRequest,
    opts ...option.RequestOption,
) (*trophygo.CreatePointsLevelsResponse, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Delete multiple points levels by ID.
func (c *Client) Delete(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request *points.LevelsDeleteRequest,
    opts ...option.RequestOption,
) (*trophygo.DeletePointsLevelsResponse, error){
    response, err := c.WithRawResponse.Delete(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Update multiple points levels. Each item must include an ID. `key` cannot be changed.
func (c *Client) Update(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request trophygo.PatchPointsLevelsRequest,
    opts ...option.RequestOption,
) (*trophygo.PatchPointsLevelsResponse, error){
    response, err := c.WithRawResponse.Update(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a single points level by ID.
func (c *Client) Get(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    // The UUID of the points level.
    id string,
    opts ...option.RequestOption,
) (*trophygo.AdminPointsLevel, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        systemId,
        id,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

