// Code generated by Fern. DO NOT EDIT.

package triggers

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    points "github.com/trophyso/trophy-go/admin/points"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.21.0"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// List points triggers for a system.
func (c *Client) List(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request *points.TriggersListRequest,
    opts ...option.RequestOption,
) (trophygo.ListPointsTriggersResponse, error){
    response, err := c.WithRawResponse.List(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Create points triggers in bulk. Maximum 100 triggers per request.
func (c *Client) Create(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request trophygo.CreatePointsTriggersRequest,
    opts ...option.RequestOption,
) (*trophygo.CreatePointsTriggersResponse, error){
    response, err := c.WithRawResponse.Create(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Delete (archive) points triggers by ID. Maximum 100 trigger IDs per request.
func (c *Client) Delete(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request *points.TriggersDeleteRequest,
    opts ...option.RequestOption,
) (*trophygo.DeletePointsTriggersResponse, error){
    response, err := c.WithRawResponse.Delete(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Update points triggers in bulk. Maximum 100 triggers per request. Only provided fields are updated; omitted fields are preserved.
func (c *Client) Update(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    request trophygo.PatchPointsTriggersRequest,
    opts ...option.RequestOption,
) (*trophygo.PatchPointsTriggersResponse, error){
    response, err := c.WithRawResponse.Update(
        ctx,
        systemId,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Get a single points trigger by ID.
func (c *Client) Get(
    ctx context.Context,
    // The UUID of the points system.
    systemId string,
    // The UUID of the points trigger.
    id string,
    opts ...option.RequestOption,
) (*trophygo.AdminPointsTrigger, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        systemId,
        id,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

