// Code generated by Fern. DO NOT EDIT.

package settings

import (
    context "context"

    trophygo "github.com/trophyso/trophy-go"
    admin "github.com/trophyso/trophy-go/admin"
    core "github.com/trophyso/trophy-go/core"
    internal "github.com/trophyso/trophy-go/internal"
    option "github.com/trophyso/trophy-go/option"
)


type Client struct {
    WithRawResponse *RawClient

    options *core.RequestOptions
    baseURL string
    caller *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
    if options.SdkVersion == "" {
        options.SdkVersion = "1.26.0"
    }
    return &Client{
        WithRawResponse: NewRawClient(options),
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
                DisableRetries: options.DisableRetries,
            },
        ),
    }
}

// Get branding, experimentation, and aggregation settings.
func (c *Client) Get(
    ctx context.Context,
    opts ...option.RequestOption,
) (*trophygo.AdminSettings, error){
    response, err := c.WithRawResponse.Get(
        ctx,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

// Update branding, experimentation, and aggregation settings.
func (c *Client) Update(
    ctx context.Context,
    request *admin.UpdateAdminSettingsRequest,
    opts ...option.RequestOption,
) (*trophygo.AdminSettings, error){
    response, err := c.WithRawResponse.Update(
        ctx,
        request,
        opts...,
    )
    if err != nil {
        return nil, err
    }
    return response.Body, nil
}

